### PR TITLE
Add basic volume control

### LINKED ISSUE #26: Simple volume control
`play` could add another argument, `volume` to allow the calling program simple control over how loud the track should be played.

### PR DESCRIPTION
**Pull request by johnthagen**
Fixes #26 

@bvssvni please review and provide your feedback.  Disclaimer: I am very new to Rust.

In particular, should `music` provide a different (simpler?) API for volume?  Exposing the `sdl_mixer` 0-128 based volume seems to break the layering `music` tries to provide.  I'm not sure what alternative is better though. 

- Should we expose a 0.0-1.0 `f64` input that means 0-100%?
- 0-100 `i32` that means 0-100%?
- Should we use `u32` instead of `isize`?

Also, should volume be optional (and max if not provided)?  I know Rust doesn't have native default parameters, but I thought I read it was possible to emulate them in some way.

### CODE REVIEW

**Comment by bvssvni** [comment]
I think `f64` with a range 0-1 is nice.

**Comment by johnthagen** [comment]
@bvssvni Changed parameter based on your input.  Let me know if there is anything else you think should be changed.

**Comment by johnthagen** [comment]
@bvssvni Let me know what you think of this latest version.  I was thinking about the problem some more and realized that it would probably be better to have a separate function exposed to control volume, that way the developer can control it after a track is played (for example if the player wants to change the volume while the game is running).

This is also how `rust-sdl2-mixer` works.  To keep it simple we just export a `set_volume` rather than trying to re-export everything that `rust-sdl2-mixer` does (if you need that, you should probably just used it directly), but I think this small change does help `piston-music` fill that initial prototype / simple use case.

**Comment by bvssvni** [comment]
Looks good! Merging.

**Pull request merged**
