### PR TITLE
Add Appveyor MSVC build

### PR DESCRIPTION
**Pull request by johnthagen**
@bvssvni Please enable an AppVeyor build for this project at https://ci.appveyor.com/project/PistonDevelopers/music before merging.

### CODE REVIEW

**Comment by bvssvni** [comment]
Added.

**Comment by johnthagen** [comment]
@bvssvni I can't seem to access the AppVeyor build. Did I guess the link name incorrectly?

**Comment by bvssvni** [comment]
https://ci.appveyor.com/project/bvssvni/music

**Comment by johnthagen** [comment]
@bvssvni  Ah I see that is for your fork. I did some reading and you could create an account for AppVeyor account for "PistonDevelopers" which would allow us to run builds off this main project.

I did some research and here are the steps: https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

The upside to this is that PRs to `music` can be AppVeyor tested directly from this project rather than having to use someone's personal fork. Also, once this is created, other Piston projects within PistonDevelopers/ could share the AppVeyor account to add CI testing for Windows if they wanted to.

**Comment by bvssvni** [comment]
This requires a separate email address for the organization.

**Pull request merged**
